---
script: rake

rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: 2.0.0

notifications:
  email:
    - yorickpeterse@gmail.com

branches:
  only:
    - master
    - develop
